# Generated by Django 4.0.4 on 2022-05-20 08:40

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board_Name', models.IntegerField()),
                ('Color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('current_status', models.CharField(choices=[('to do', 'To do'), ('in progress', 'In Progress'), ('on hold', 'On Hold'), ('complated', 'Complated'), ('released', 'Released')], max_length=200)),
                ('Board_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Board.board')),
            ],
        ),
    ]
